Repository FaruqRahmadani/Presensi-Guru-2, pull requests merged in 2018-11, with the labels that each got.

#68 menambahi padding dibawahnya aja sekira isinya nayamn diliat tpi mun …
  public/js/app.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
Labels: Need Attention!!!

#63 Backend/dashboard
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/HomeController.php
  app/Jenjang.php
  app/Sekolah.php
  package-lock.json
  package.json
  public/js/app.js
  resources/assets/js/_isiChart.js
  resources/assets/js/_isiChartJs.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartJenjangBar.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
  resources/assets/js/_mentah/dataMorris.js
  resources/assets/js/app.js
  resources/views/Layouts/master.blade.php
  resources/views/dashboard/dashboard.blade.php
  routes/api.php
  routes/web.php
Labels: DONE

#54 Feat/dashboard
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/HomeController.php
  app/Jenjang.php
  app/Sekolah.php
  package-lock.json
  package.json
  public/css/app.css
  resources/assets/js/_isiChartJs.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartJenjangBar.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
  resources/assets/js/_mentah/dataMorris.js
  resources/assets/js/app.js
  resources/assets/sass/_mentah/_custom.scss
  resources/views/Layouts/master.blade.php
  resources/views/dashboard/dashboard.blade.php
  routes/api.php
  routes/web.php
Labels: DONE

#69 perbaikan bug merge
  public/css/app.css
  public/js/app.js
  resources/views/Layouts/master.blade.php
Labels: DONE, Need Attention!!!

#71 Backend/admin sekolah/data sekolah
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/SekolahSayaController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminSekolahMiddleware.php
  app/Http/Middleware/SuperAdminMiddleware.php
  app/Jenjang.php
  app/Sekolah.php
  app/User.php
  package-lock.json
  package.json
  public/css/app.css
  public/js/app.js
  resources/assets/js/_isiChartJs.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartJenjangBar.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
  resources/assets/js/_mentah/dataMorris.js
  resources/assets/js/app.js
  resources/assets/sass/_mentah/_custom.scss
  resources/assets/sass/_mentah/_login.scss
  resources/assets/sass/_mentah/_select2.scss
  resources/assets/sass/_mentah/_variable.scss
  resources/views/Layouts/master.blade.php
  resources/views/Layouts/sidebarAdmin.blade.php
  resources/views/Layouts/sidebarAdminSekolah.blade.php
  resources/views/dashboard/dashboard.blade.php
  resources/views/presensi/data.blade.php
  resources/views/sekolah/adminSekolah-edit.blade.php
  resources/views/sekolah/adminSekolah-info.blade.php
  resources/views/sekolahSaya/edit.blade.php
  resources/views/sekolahSaya/info.blade.php
  routes/api.php
  routes/web.php
Labels: DONE

#72 Backend/admin sekolah/data pegawai
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/PegawaiSekolahController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminSekolahMiddleware.php
  app/Http/Middleware/SuperAdminMiddleware.php
  app/Jenjang.php
  app/Sekolah.php
  app/User.php
  package-lock.json
  package.json
  public/css/app.css
  public/js/app.js
  resources/assets/js/_isiChartJs.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartJenjangBar.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
  resources/assets/js/_mentah/dataMorris.js
  resources/assets/js/app.js
  resources/assets/sass/_mentah/_custom.scss
  resources/assets/sass/_mentah/_login.scss
  resources/assets/sass/_mentah/_select2.scss
  resources/assets/sass/_mentah/_variable.scss
  resources/views/Layouts/master.blade.php
  resources/views/Layouts/sidebarAdmin.blade.php
  resources/views/Layouts/sidebarAdminSekolah.blade.php
  resources/views/dashboard/dashboard.blade.php
  resources/views/pegawai/adminSekolah-data.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  resources/views/pegawaiSekolah/edit.blade.php
  resources/views/pegawaiSekolah/tambah.blade.php
  resources/views/presensi/data.blade.php
  routes/api.php
  routes/web.php
Labels: DONE

#56 penambahan halaman data dan formInput datapegawai
  app/Http/Controllers/PegawaiSekolahController.php
  resources/views/Layouts/sidebarAdminSekolah.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  resources/views/pegawaiSekolah/edit.blade.php
  resources/views/pegawaiSekolah/tambah.blade.php
  routes/web.php
Labels: DONE

#73 Backend/admin sekolah/jam kerja
  app/Helpers/DateHelper.php
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/JamKerjaController.php
  app/Http/Controllers/PegawaiSekolahController.php
  app/Http/Controllers/SekolahSayaController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminSekolahMiddleware.php
  app/Http/Middleware/SuperAdminMiddleware.php
  app/JamKerja.php
  app/Jenjang.php
  app/Repositories/JamKerjaRepository.php
  app/Sekolah.php
  app/User.php
  database/factories/JamKerjaFactory.php
  package-lock.json
  package.json
  public/css/app.css
  public/js/app.js
  resources/assets/js/_isiChartJs.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartJenjangBar.js
  resources/assets/js/_mentah/_chartJenjangPie.js
  resources/assets/js/_mentah/_chartSekolah.js
  resources/assets/js/_mentah/dataMorris.js
  resources/assets/js/app.js
  resources/assets/sass/_mentah/_custom.scss
  resources/assets/sass/_mentah/_login.scss
  resources/assets/sass/_mentah/_select2.scss
  resources/assets/sass/_mentah/_variable.scss
  resources/views/Layouts/master.blade.php
  resources/views/Layouts/sidebarAdmin.blade.php
  resources/views/Layouts/sidebarAdminSekolah.blade.php
  resources/views/dashboard/dashboard.blade.php
  resources/views/jamKerja/adminSekolah-data.blade.php
  resources/views/jamKerja/data.blade.php
  resources/views/jamKerja/edit.blade.php
  resources/views/jamKerja/tambah.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  resources/views/pegawaiSekolah/edit.blade.php
  resources/views/pegawaiSekolah/tambah.blade.php
  resources/views/presensi/data.blade.php
  resources/views/sekolahSaya/edit.blade.php
  resources/views/sekolahSaya/info.blade.php
  routes/api.php
  routes/web.php
Labels: DONE

#59 tambah halaman data dan tambah jam kerja
  app/Helpers/DateHelper.php
  app/Http/Controllers/JamKerjaController.php
  app/JamKerja.php
  app/Repositories/JamKerjaRepository.php
  database/factories/JamKerjaFactory.php
  resources/views/Layouts/sidebarAdminSekolah.blade.php
  resources/views/jamKerja/data.blade.php
  resources/views/jamKerja/edit.blade.php
  resources/views/jamKerja/tambah.blade.php
  routes/web.php
Labels: DONE

#76 Hotfix akibat perubahan method repository model
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AdminSekolahController.php
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/JamKerjaController.php
  app/Http/Controllers/PegawaiSekolahController.php
  app/Http/Controllers/SekolahController.php
  app/Http/Controllers/SekolahSayaController.php
  app/Repositories/Repository.php
Labels: DONE, Need Attention!!!

#78 Styling/datatable
  public/js/app.js
  resources/assets/js/_mentah/_datatable.js
  resources/views/admin/data.blade.php
  resources/views/adminSekolah/data.blade.php
  resources/views/jamKerja/data.blade.php
  resources/views/jamKerja/edit.blade.php
  resources/views/jamKerja/tambah.blade.php
  resources/views/jenjangSekolah/data.blade.php
  resources/views/kategoriPresensi/data.blade.php
  resources/views/kategoriPresensi/edit.blade.php
  resources/views/kategoriPresensi/tambah.blade.php
  resources/views/pegawai/data.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  resources/views/pegawaiSekolah/edit.blade.php
  resources/views/pegawaiSekolah/tambah.blade.php
  resources/views/presensi/data.blade.php
  resources/views/sekolah/data.blade.php
  resources/views/statusSekolah/data.blade.php
  resources/views/statusSekolah/edit.blade.php
  resources/views/statusSekolah/tambah.blade.php
Labels: DONE

#82 Backend/super admin/data presensi
  app/Http/Controllers/PresensiController.php
  resources/views/Layouts/sidebarAdmin.blade.php
  resources/views/presensi/data.blade.php
  routes/web.php
Labels: DONE

#93 Backend/statistik pegawai
  app/Http/Controllers/ApiController.php
  public/js/app.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartStatistikPegawaiDonat.js
  resources/views/pegawai/data.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  routes/api.php
Labels: DONE

#88 Feat/statistik pegawai
  app/Http/Controllers/ApiController.php
  public/js/app.js
  resources/assets/js/_mentah/_chart.js
  resources/assets/js/_mentah/_chartStatistikPegawaiDonat.js
  resources/assets/js/_mentah/_chartStatistikPegawaiDonatSU.js
  resources/views/Layouts/master.blade.php
  resources/views/pegawai/data.blade.php
  resources/views/pegawaiSekolah/data.blade.php
  routes/api.php
Labels: DONE
